### ISSUE TITLE
URL config is not working:

### ISSUE THREAD

**Issue by piperod** [compiteing/flask-ponywhoosh#12]
I tried to use the url in the example.py 

before was:
app.config['PONYWHOOSH_URL'] = '/ponywhoosh'

I changed to: 
app.config['PONYWHOOSH_URL'] = '/'

but it didn't change internally. 

I had to go to pony whoosh and it was by default /ponywhoosh/ . Can we check this?

**Comment by jonaprieto** [comment]
it occurs with another url? or it just definitively doesn't work at all?

**Comment by piperod** [comment]
I tried several configurations and no one actually worked.
