### ISSUE TITLE
ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.

### ISSUE THREAD

**Issue by clach04** [compiteing/flask-ponywhoosh#3]
pip3 install flask-ponywhoosh

completes, then get example.py from 
https://github.com/compiteing/flask-ponywhoosh/blob/e11c402df7a7ee0324c0323f17e179d61464e7fb/example.py and attempt to run with Python 3.5.1:

    C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.
      .format(x=modname), ExtDeprecationWarning
    C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
      .format(x=modname), ExtDeprecationWarning
    Traceback (most recent call last):
      File "example.py", line 11, in <module>
        from flask.ext.script import Manager, Shell
      File "C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask\exthook.py", line 110, in load_module
        raise ImportError('No module named %s' % fullname)
    ImportError: No module named flask.ext.script

However flask_bootstrap is present in setup.py and requirements.txt  and pip log shows it was installed:

    Collecting flask-ponywhoosh
      Downloading Flask-PonyWhoosh-0.2.tar.gz
    Collecting flask (from flask-ponywhoosh)
      Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
        100% |################################| 81kB 1.1MB/s
    Collecting ponywhoosh (from flask-ponywhoosh)
      Downloading ponywhoosh-1.7.tar.gz
    Collecting flask-bootstrap (from flask-ponywhoosh)
      Downloading Flask-Bootstrap-3.3.7.0.tar.gz (456kB)
        100% |################################| 458kB 431kB/s
    Collecting flask-wtf (from flask-ponywhoosh)
      Downloading Flask-WTF-0.12.tar.gz (247kB)
        100% |################################| 249kB 819kB/s
    Collecting itsdangerous>=0.21 (from flask->flask-ponywhoosh)
      Downloading itsdangerous-0.24.tar.gz (46kB)
        100% |################################| 49kB 1.7MB/s
    Collecting Werkzeug>=0.7 (from flask->flask-ponywhoosh)
      Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
    Collecting Jinja2>=2.4 (from flask->flask-ponywhoosh)
      Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
        100% |################################| 266kB 1.2MB/s
    Collecting click>=2.0 (from flask->flask-ponywhoosh)
      Downloading click-6.6.tar.gz (283kB)
        100% |################################| 286kB 413kB/s
    Collecting pony (from ponywhoosh->flask-ponywhoosh)
      Downloading pony-0.6.6.zip (276kB)
        100% |################################| 278kB 744kB/s
    Collecting whoosh (from ponywhoosh->flask-ponywhoosh)
      Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468kB)
        100% |################################| 471kB 375kB/s
    Collecting dominate (from flask-bootstrap->flask-ponywhoosh)
      Downloading dominate-2.2.1.zip (46kB)
        100% |################################| 49kB 1.7MB/s
    Collecting visitor (from flask-bootstrap->flask-ponywhoosh)
      Downloading visitor-0.1.3.tar.gz
    Collecting WTForms (from flask-wtf->flask-ponywhoosh)
      Downloading WTForms-2.1.zip (553kB)
        100% |################################| 557kB 365kB/s
    Collecting MarkupSafe (from Jinja2>=2.4->flask->flask-ponywhoosh)
      Downloading MarkupSafe-0.23.tar.gz
    Installing collected packages: itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, flask, pony, whoosh, ponywhoosh, dominate, visitor, flask-bootstrap, WTForms,
    flask-wtf, flask-ponywhoosh
      Running setup.py install for itsdangerous
      Running setup.py install for MarkupSafe
      Running setup.py install for click
      Running setup.py install for pony
      Running setup.py install for ponywhoosh
      Running setup.py install for dominate
      Running setup.py install for visitor
      Running setup.py install for flask-bootstrap
      Running setup.py install for WTForms
      Running setup.py install for flask-wtf
      Running setup.py install for flask-ponywhoosh
    Successfully installed Jinja2-2.8 MarkupSafe-0.23 WTForms-2.1 Werkzeug-0.11.11 click-6.6 dominate-2.2.1 flask-0.11.1 flask-bootstrap-3.3.7.0 flask-ponywhoosh-0.2 flask-wtf-0.12 itsdangerous-0.24 pony-0.6.6 ponywhoosh-1.7 visitor-0.1.3 whoosh-2.7.4

**Comment by clach04** [comment]
Updating example.py to use;

    from flask_bootstrap import Bootstrap
    from flask_script import Manager, Shell

Then fails with a different message:

    Traceback (most recent call last):
      File "example.py", line 15, in <module>
        from flask_ponywhoosh import PonyWhoosh
      File "C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask_ponywhoosh\__init__.py", line 40
        if app is not None:
                          ^
    TabError: inconsistent use of tabs and spaces in indentation


Line 38, first line of PonyWhoosh() is indented with a tab. Fixing this then leads to:

    Traceback (most recent call last):
      File "example.py", line 15, in <module>
        from flask_ponywhoosh import PonyWhoosh
      File "C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask_ponywhoosh\__init__.py", line 66
        print 'PONYWHOOSH_DEBUG -> ', self.debug
                                   ^
    SyntaxError: Missing parentheses in call to 'print'

There are multiple py2.x print statements.

Fixing those leads to:

    Traceback (most recent call last):
      File "example.py", line 15, in <module>
        from flask_ponywhoosh import PonyWhoosh
      File "C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\flask_ponywhoosh\__init__.py", line 16, in <module>
        from ponywhoosh import PonyWhoosh as MyPonyWhoosh
      File "C:\Users\clach04\py\pony_whoosh_flask\p3PonyWooshFlask\lib\site-packages\ponywhoosh\__init__.py", line 13, in <module>
        from core import PonyWhoosh
    ImportError: No module named 'core'


Fixing that via:

    from ponywhoosh.core import PonyWhoosh

Then leads to more print statement issues

**Comment by clach04** [comment]
Python 2.7 with:

    pip install flask-ponywhoosh flask_script

and update example as per above allows:

    python example.py runserver

to run

**Comment by jonaprieto** [comment]
The `print` issues is because to date we don't have support for python 3. And with python 2.7 everything should be fine. Without any update, it is failing?

**Comment by clach04** [comment]
Sorry, my mistake! I'd been reading PonyORM docs and saw py3 support (and dropping py2.6) and got that lodged in my brain. I just logged pull request #4 for the example update to use the non-deprecated Flask pieces

**Comment by jonaprieto** [comment]
Your PR was accepted. Thanks.
